name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *" # At midnight & noon UTC

jobs:
  scrape2:
    runs-on: ubuntu-latest
    needs: scrape1
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Fetch sponsor data
        run: python ./main2.py
